# Import

In [45]:
import pandas as pd

# Ouverture CSV

In [46]:
df_normal = pd.read_csv('../data/Network datatset/raw_csv/normal.csv', delimiter=',', header=0)

df_attack_1 = pd.read_csv('../data/Network datatset/raw_csv/attack_1.csv', delimiter=',', header=0)
df_attack_2 = pd.read_csv('../data/Network datatset/raw_csv/attack_2.csv', delimiter=',', header=0)
df_attack_3 = pd.read_csv('../data/Network datatset/raw_csv/attack_3.csv', delimiter=',', header=0)
df_attack_4 = pd.read_csv('../data/Network datatset/raw_csv/attack_4.csv', delimiter=',', header=0)

# Uniformisation des headers

In [50]:
# Change the name of the columns by removing the spaces
for df_attack in [df_attack_1, df_attack_2, df_attack_3, df_attack_4]:
    df_attack.columns = df_attack.columns.str.replace(' ', '')

# Merge des DataFrame

In [51]:
df = pd.concat([df_normal, df_attack_1, df_attack_2, df_attack_3, df_attack_4])

In [52]:
df.shape

(29829204, 16)

In [54]:
df.head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-09 11:30:52.716203,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,61516.0,502.0,Modbus,11000.0,66,Read Holding Registers,0.0,0.0,NaN,0,normal
1,2021-04-09 11:30:52.716499,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,502.0,61516.0,Modbus,11000.0,65,Read Holding Registers Response,0.0,0.0,[0],0,normal
2,2021-04-09 11:30:52.717334,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,61515.0,502.0,Modbus,11000.0,66,Read Holding Registers,1.0,0.0,NaN,0,normal
3,2021-04-09 11:30:52.717624,e6:3f:ac:c9:a8:8c,74:46:a0:bd:a7:1b,84.3.251.101,84.3.251.20,502.0,61515.0,Modbus,11000.0,65,Read Holding Registers Response,0.0,1.0,[0],0,normal
4,2021-04-09 11:30:52.717952,00:80:f4:03:fb:12,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,502.0,61514.0,Modbus,11000.0,64,Read Coils Response,0.0,2.0,[0],0,normal

# Clean colonne par colonne

## Time

Pas d'utilité

In [55]:
df = df.drop(columns=['Time'])

In [56]:
df.head()

,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,61516.0,502.0,Modbus,11000.0,66,Read Holding Registers,0.0,0.0,NaN,0,normal
1,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,502.0,61516.0,Modbus,11000.0,65,Read Holding Registers Response,0.0,0.0,[0],0,normal
2,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,61515.0,502.0,Modbus,11000.0,66,Read Holding Registers,1.0,0.0,NaN,0,normal
3,e6:3f:ac:c9:a8:8c,74:46:a0:bd:a7:1b,84.3.251.101,84.3.251.20,502.0,61515.0,Modbus,11000.0,65,Read Holding Registers Response,0.0,1.0,[0],0,normal
4,00:80:f4:03:fb:12,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,502.0,61514.0,Modbus,11000.0,64,Read Coils Response,0.0,2.0,[0],0,normal

## mac_s

On garde

In [60]:
df['mac_s'].value_counts(dropna=False)

mac_s
74:46:a0:bd:a7:1b    12022067
e6:3f:ac:c9:a8:8c     3826187
0a:fe:ec:47:74:fb     3790401
fa:00:bc:90:d7:fa     3746944
00:0c:29:47:8c:22     3464019
00:0c:29:47:8c:0e     1553893
00:80:f4:03:fb:12     1293899
fe:bb:16:7b:c3:27       66015
4a:35:83:e0:3d:a4       65779
Name: count, dtype: int64

## mac_d

On garde

In [61]:
df['mac_d'].value_counts(dropna=False)

mac_d
74:46:a0:bd:a7:1b    12218994
00:80:f4:03:fb:12     6092086
e6:3f:ac:c9:a8:8c     3841183
0a:fe:ec:47:74:fb     3812304
fa:00:bc:90:d7:fa     3746073
fe:bb:16:7b:c3:27       49022
4a:35:83:e0:3d:a4       48812
00:0c:29:47:8c:22       18295
00:0c:29:47:8c:0e        1753
ff:ff:ff:ff:ff:ff         682
Name: count, dtype: int64

## ip_s

1379 valeurs null

On garde

In [62]:
df['ip_s'].value_counts(dropna=False)

ip_s
84.3.251.20     13441115
84.3.251.103     4368164
84.3.251.101     3849830
84.3.251.102     3793240
84.3.251.110     2948185
84.3.251.18      1294781
84.3.251.104       66554
84.3.251.105       65956
NaN                 1379
Name: count, dtype: int64

In [63]:
df = df.dropna(subset=['ip_s'])

In [64]:
df.head()

,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,61516.0,502.0,Modbus,11000.0,66,Read Holding Registers,0.0,0.0,NaN,0,normal
1,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,502.0,61516.0,Modbus,11000.0,65,Read Holding Registers Response,0.0,0.0,[0],0,normal
2,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,61515.0,502.0,Modbus,11000.0,66,Read Holding Registers,1.0,0.0,NaN,0,normal
3,e6:3f:ac:c9:a8:8c,74:46:a0:bd:a7:1b,84.3.251.101,84.3.251.20,502.0,61515.0,Modbus,11000.0,65,Read Holding Registers Response,0.0,1.0,[0],0,normal
4,00:80:f4:03:fb:12,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,502.0,61514.0,Modbus,11000.0,64,Read Coils Response,0.0,2.0,[0],0,normal

## ip_d

On garde

In [66]:
df['ip_d'].value_counts(dropna=False)

ip_d
84.3.251.20     12218971
84.3.251.18      6092951
84.3.251.101     3842616
84.3.251.102     3815977
84.3.251.103     3747951
84.3.251.104       49377
84.3.251.105       49022
84.3.251.110       10960
Name: count, dtype: int64

## sport

1379 valeurs null

On garde

In [67]:
df['sport'].value_counts(dropna=False)

sport
502.0      12365484
NaN         4623661
61515.0     1139912
61517.0     1139743
61516.0     1139708
             ...
46538.0           5
46534.0           5
46530.0           5
46528.0           5
1131.0            5
Name: count, Length: 65537, dtype: int64

In [ ]:
df = df.dropna(subset=['ip_s'])

In [ ]:
df.head()

,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,61516.0,502.0,Modbus,11000.0,66,Read Holding Registers,0.0,0.0,NaN,0,normal
1,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,502.0,61516.0,Modbus,11000.0,65,Read Holding Registers Response,0.0,0.0,[0],0,normal
2,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,61515.0,502.0,Modbus,11000.0,66,Read Holding Registers,1.0,0.0,NaN,0,normal
3,e6:3f:ac:c9:a8:8c,74:46:a0:bd:a7:1b,84.3.251.101,84.3.251.20,502.0,61515.0,Modbus,11000.0,65,Read Holding Registers Response,0.0,1.0,[0],0,normal
4,00:80:f4:03:fb:12,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,502.0,61514.0,Modbus,11000.0,64,Read Coils Response,0.0,2.0,[0],0,normal